### ISSUE TITLE
`__future__` in solution notebooks in QuantEcon.applications

### ISSUE THREAD

**Issue by oyamad** [OyamaZemi/sprints#2]
```
$ grep "__future__" */*.ipynb
arellano/arellano_solutions_py.ipynb:    "from __future__ import division\n",
discrete_dp/discrete_dp_solutions_py.ipynb:    "from __future__ import division, print_function\n",
finite_markov/finite_mc_solutions_py.ipynb:      "from __future__ import print_function, division  # Omit for Python 3.x\n",
kalman/kalman_solutions_py.ipynb:    "from __future__ import print_function  # Remove for Python 3.x\n",
linear_models/lss_solutions_py.ipynb:    "from __future__ import division\n",
lqcontrol/lqcontrol_solutions_py.ipynb:      "from __future__ import division\n",
lucas_model/lucas_asset_solutions_py.ipynb:    "from __future__ import division  # Omit for Python 3.x\n",
optgrowth/optgrowth_solutions_py.ipynb:    "from __future__ import division  # Not needed for Python 3.x\n",
python_by_example/pbe_solutions.ipynb:      "from __future__ import division  # Omit if using Python 3.x\n",
python_essentials/pyess_solutions.ipynb:      "from __future__ import division  # Omit for Python 3.x"
rational_expectations/ree_solutions_py.ipynb:      "from __future__ import print_function\n",
uncertainty_traps/uncertainty_traps_solutions_py.ipynb:    "from __future__ import division\n",
```

**Comment by myuuuuun** [comment]
lucas_model よりも下をやります

**Comment by nswa17** [comment]
arellano_solutions_py ふたつ目のセルを実行すると

---

ImportError                               Traceback (most recent call last)
<ipython-input-12-f2d37cacec0d> in <module>()
      3 import matplotlib.pyplot as plt
      4 import quantecon as qe
----> 5 from quantecon.models import Arellano_Economy

/Users/neon/anaconda/lib/python3.5/site-packages/quantecon/models/**init**.py in <module>()
----> 1 raise ImportError("The code previously contained in the quantecon.models subpackage has been migrated to the QuantEcon.applications (https://github.com/QuantEcon/QuantEcon.applications) repo")

ImportError: The code previously contained in the quantecon.models subpackage has been migrated to the QuantEcon.applications (https://github.com/QuantEcon/QuantEcon.applications) repo

というエラーが出ました.

**Comment by oyamad** [comment]
エラーメッセージにあるとおりで，`from quantecon.models` が書いてある notebook は今回は触らないでおく．

最後 pull request を出すときに `from quantecon.models` が書いてある notebook のリストを書く．
